/*
-- Query: SELECT * FROM ehairdressing.customer
LIMIT 0, 1000

-- Date: 2015-04-25 07:20
*/
INSERT INTO `customer` (`ID`,`CREATIONDATE`,`DATEOFBIRTH`,`GENDER`,`MOBILEPHONE`,`NAME`,`PASSWORD`,`SURNAME`,`USERNAME`,`CITY`,`PROVINCE`,`STREET`,`ZIPCODE`) VALUES (1000,NULL,'1976-06-14',NULL,'615095361','Ruben',NULL,'Sanchez Sancho','rsanchezs@uoc.edu',NULL,NULL,NULL,NULL);
INSERT INTO `customer` (`ID`,`CREATIONDATE`,`DATEOFBIRTH`,`GENDER`,`MOBILEPHONE`,`NAME`,`PASSWORD`,`SURNAME`,`USERNAME`,`CITY`,`PROVINCE`,`STREET`,`ZIPCODE`) VALUES (1001,NULL,'1974-05-07',NULL,'676208094','Marga',NULL,'Alfara Filella','assessoramentimatge@hotmail.com',NULL,NULL,NULL,NULL);
